// Type definitions for database enums
// These match the string values stored in the database

export enum ProjectStatus {
  INITIAL_CONTACT = 'INITIAL_CONTACT',
  QUOTE_SENT = 'QUOTE_SENT',
  QUOTE_APPROVED = 'QUOTE_APPROVED',
  CONTRACT_SIGNED = 'CONTRACT_SIGNED',
  PAYMENT_RECEIVED = 'PAYMENT_RECEIVED',
  PARTS_ORDERED = 'PARTS_ORDERED',
  PARTS_RECEIVED = 'PARTS_RECEIVED',
  INSTALLATION_SCHEDULED = 'INSTALLATION_SCHEDULED',
  INSTALLATION_IN_PROGRESS = 'INSTALLATION_IN_PROGRESS',
  INSTALLATION_COMPLETE = 'INSTALLATION_COMPLETE',
  FINAL_INSPECTION = 'FINAL_INSPECTION',
  PROJECT_COMPLETE = 'PROJECT_COMPLETE',
  ON_HOLD = 'ON_HOLD',
  CANCELLED = 'CANCELLED',
}

export enum MilestoneStatus {
  PENDING = 'PENDING',
  PENDING_WAITING_FOR_INFO = 'PENDING_WAITING_FOR_INFO',
  PENDING_SCHEDULED = 'PENDING_SCHEDULED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  ON_HOLD = 'ON_HOLD',
}

